/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CustomProblemDetails {
    type?: string;
    title?: string;
    status?: number;
    detail?: string;
    instance?: string;
}
