/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Education {
    /** Id property for education item. */
    id?: string;
    /** Title of the degree or certification. */
    title?: string;
    /** Subtitle of the degree or certification. */
    subtitle?: string;
    /** Issuing organization for the education item. */
    organization?: string;
}
