/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as NgResumeApi from "..";

export interface User {
    id?: string;
    userPrincipalName?: string;
    displayName?: string;
    givenName?: string;
    surname?: string;
    identities?: NgResumeApi.Identity[];
    memberOf?: NgResumeApi.Group[];
}
