/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface WorkHistory {
    /** Id property for the work history item. */
    id?: string;
    /** Starting year for the work history item. */
    startYear?: number;
    /** Ending year for the work history item. */
    endYear?: number;
    /** Role title for the work history item. */
    title?: string;
    /** Organization of the work history item. */
    organization?: string;
    /** URL for the organization of the work history item. */
    organizationUrl?: string;
    /** Array of bullets to display with the work history item. */
    bullets?: string[];
    /** Array of skills exercised with the role in the work history item. */
    skills?: string[];
}
