/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as NgResumeApi from "../../api";
import * as core from "../../core";

export const CustomProblemDetails: core.serialization.ObjectSchema<
    serializers.CustomProblemDetails.Raw,
    NgResumeApi.CustomProblemDetails
> = core.serialization.object({
    type: core.serialization.string().optional(),
    title: core.serialization.string().optional(),
    status: core.serialization.number().optional(),
    detail: core.serialization.string().optional(),
    instance: core.serialization.string().optional(),
});

export declare namespace CustomProblemDetails {
    interface Raw {
        type?: string | null;
        title?: string | null;
        status?: number | null;
        detail?: string | null;
        instance?: string | null;
    }
}
