/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as NgResumeApi from "../../api";
import * as core from "../../core";

export const Education: core.serialization.ObjectSchema<serializers.Education.Raw, NgResumeApi.Education> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        title: core.serialization.string().optional(),
        subtitle: core.serialization.string().optional(),
        organization: core.serialization.string().optional(),
    });

export declare namespace Education {
    interface Raw {
        id?: string | null;
        title?: string | null;
        subtitle?: string | null;
        organization?: string | null;
    }
}
