/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as NgResumeApi from "../../api";
import * as core from "../../core";

export const Test: core.serialization.ObjectSchema<serializers.Test.Raw, NgResumeApi.Test> = core.serialization.object({
    id: core.serialization.string().optional(),
    message: core.serialization.string().optional(),
});

export declare namespace Test {
    interface Raw {
        id?: string | null;
        message?: string | null;
    }
}
