/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as NgResumeApi from "../../api";
import * as core from "../../core";

export const User: core.serialization.ObjectSchema<serializers.User.Raw, NgResumeApi.User> = core.serialization.object({
    id: core.serialization.string().optional(),
    displayName: core.serialization.string().optional(),
    mail: core.serialization.string().optional(),
    identities: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("..")).Identity))
        .optional(),
    memberOf: core.serialization.list(core.serialization.lazyObject(async () => (await import("..")).Group)).optional(),
});

export declare namespace User {
    interface Raw {
        id?: string | null;
        displayName?: string | null;
        mail?: string | null;
        identities?: serializers.Identity.Raw[] | null;
        memberOf?: serializers.Group.Raw[] | null;
    }
}
