/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as NgResumeApi from "../../api";
import * as core from "../../core";

export const User: core.serialization.ObjectSchema<serializers.User.Raw, NgResumeApi.User> = core.serialization.object({
    id: core.serialization.string().optional(),
});

export declare namespace User {
    interface Raw {
        id?: string | null;
    }
}
