/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "..";
import * as JpfultonApi from "../../api";
import * as core from "../../core";

export const WorkHistory: core.serialization.ObjectSchema<serializers.WorkHistory.Raw, JpfultonApi.WorkHistory> =
    core.serialization.object({
        id: core.serialization.string().optional(),
        startYear: core.serialization.number().optional(),
        endYear: core.serialization.number().optional(),
        title: core.serialization.string().optional(),
        organization: core.serialization.string().optional(),
        organizationUrl: core.serialization.property("organizationURL", core.serialization.string().optional()),
        bullets: core.serialization.list(core.serialization.string()).optional(),
        skills: core.serialization.list(core.serialization.string()).optional(),
    });

export declare namespace WorkHistory {
    interface Raw {
        id?: string | null;
        startYear?: number | null;
        endYear?: number | null;
        title?: string | null;
        organization?: string | null;
        organizationURL?: string | null;
        bullets?: string[] | null;
        skills?: string[] | null;
    }
}
