/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Education } from "./api/resources/education/client/Client";
import { Profile } from "./api/resources/profile/client/Client";
import { Test } from "./api/resources/test/client/Client";
import { Users } from "./api/resources/users/client/Client";
import { Workhistory } from "./api/resources/workhistory/client/Client";

export declare namespace NgResumeApiClient {
    interface Options {
        environment?: core.Supplier<environments.NgResumeApiEnvironment | string>;
        token?: core.Supplier<core.BearerToken | undefined>;
        fetcher?: core.FetchFunction;
    }
}

export class NgResumeApiClient {
    constructor(protected readonly _options: NgResumeApiClient.Options) {}

    protected _education: Education | undefined;

    public get education(): Education {
        return (this._education ??= new Education(this._options));
    }

    protected _profile: Profile | undefined;

    public get profile(): Profile {
        return (this._profile ??= new Profile(this._options));
    }

    protected _test: Test | undefined;

    public get test(): Test {
        return (this._test ??= new Test(this._options));
    }

    protected _users: Users | undefined;

    public get users(): Users {
        return (this._users ??= new Users(this._options));
    }

    protected _workhistory: Workhistory | undefined;

    public get workhistory(): Workhistory {
        return (this._workhistory ??= new Workhistory(this._options));
    }
}
