/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const NgResumeApiEnvironment = {
    Default: "/api/",
} as const;

export type NgResumeApiEnvironment = typeof NgResumeApiEnvironment.Default;
