/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const JpfultonApiEnvironment = {
    Default: "/api/",
} as const;

export type JpfultonApiEnvironment = typeof JpfultonApiEnvironment.Default;
