/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import * as JpfultonApi from "../../../../api";
import * as core from "../../../../core";

export const Response: core.serialization.Schema<
    serializers.workhistory.workHistoryGetAll.Response.Raw,
    JpfultonApi.WorkHistory[]
> = core.serialization.list(core.serialization.lazyObject(async () => (await import("../../..")).WorkHistory));

export declare namespace Response {
    type Raw = serializers.WorkHistory.Raw[];
}
