name: ci

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    permissions:
      contents: read # for actions/checkout to fetch code
      checks: write
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v3

      - name: Install Dependencies
        run: yarn install

      - name: Danger
        if: (github.event_name == 'pull_request' && github.event.action != 'closed')
        uses: jpfulton/danger-js-action@main
        with:
          dangerfile: https://raw.githubusercontent.com/jpfulton/jpfulton-devops-config/main/danger-files/dangerfile-node-project.ts
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Compile
        run: yarn build
  
  publish:
    needs: [ compile ]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up node
        uses: actions/setup-node@v3

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Publish to npm
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}